workspace:
  base: /go
  path: src/bosun.org/

clone:
  clone:
    image: 325714046698.dkr.ecr.eu-west-1.amazonaws.com/dmx/drone-git:next
    pull: true

pipeline:
  test:
    image: golang:1.11.5-stretch
    environment:
      - AWS_ACCESS_KEY_ID=$$CLOUDWATCH_ACCESSKEY
      - AWS_SECRET_ACCESS_KEY=$$CLOUDWATCH_SECRET_ACCESSKEY
      - GOPATH=/go
    commands:
      - go test -v bosun.org/...

  build_bosun:
    image: golang:1.11.5-stretch
    environment:
      - GOPATH=/go
    commands:
      - cd cmd/bosun
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bosun -tags esv5

  build_scollector:
    image: golang:1.11.5-stretch
    environment:
      - GOPATH=/go
    commands:
      - cd cmd/scollector
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o scollector -tags esv5

  prod_bosun_snapshot:
    image: plugins/s3
    region: eu-west-1
    bucket: skyscanner-prod-skymetrics-deploymentsupport
    acl: bucket-owner-full-control
    secrets:
      - source: prod_accesskey
        target: aws_access_key_id
      - source: prod_secretkey
        target: aws_secret_access_key
    source: /go/src/bosun.org/cmd/bosun/bosun
    target: /artifacts/bosun/${DRONE_BRANCH}-0.6.0-1.0.${DRONE_BUILD_NUMBER}/bosun
    strip_prefix: /go/src/bosun.org/cmd/bosun/bosun
    when:
      branch:
        exclude: master
      event:
        exclude: [pull_request, tag]

  prod_bosun:
    image: plugins/s3
    region: eu-west-1
    bucket: skyscanner-prod-skymetrics-deploymentsupport
    acl: bucket-owner-full-control
    secrets:
      - source: prod_accesskey
        target: aws_access_key_id
      - source: prod_secretkey
        target: aws_secret_access_key
    source: /go/src/bosun.org/cmd/bosun/bosun
    target: /artifacts/bosun/${DRONE_TAG}/bosun
    strip_prefix: /go/src/bosun.org/cmd/bosun/bosun
    when:
      event: tag

#  sandbox_scollector_snapshot:
#    image: plugins/s3
#    region: eu-west-1
#    bucket: skyscanner-sandbox-skymetrics-deploymentsupport
#    acl: bucket-owner-full-control
#    secrets:
#      - source: sandbox_accesskey
#        target: aws_access_key_id
#      - source: sandbox_secretkey
#        target: aws_secret_access_key
#    source: /go/src/bosun.org/cmd/scollector/scollector
#    target: /artifacts/scollector/${DRONE_BRANCH}-0.6.0-1.0.${DRONE_BUILD_NUMBER}/scollector
#    strip_prefix: /go/src/bosun.org/cmd/scollector/scollector
#    when:
#      branch:
#        exclude: master
#      event:
#        exclude: [pull_request, tag]

  #sandbox_scollector:
  #  image: plugins/s3
  #  region: eu-west-1
  #  bucket: skyscanner-sandbox-skymetrics-deploymentsupport
  #  acl: bucket-owner-full-control
  #  secrets:
  #    - source: sandbox_accesskey
  #      target: aws_access_key_id
  #    - source: sandbox_secretkey
  #      target: aws_secret_access_key
  #  source: /go/src/bosun.org/cmd/scollector/scollector
  #  target: /artifacts/scollector/${DRONE_TAG}/scollector
  #  strip_prefix: /go/src/bosun.org/cmd/scollector/scollector
  #  when:
  #    event: tag

  prod_scollector:
    image: plugins/s3
    region: eu-west-1
    bucket: skyscanner-prod-skymetrics-deploymentsupport
    acl: bucket-owner-full-control
    secrets:
      - source: prod_accesskey
        target: aws_access_key_id
      - source: prod_secretkey
        target: aws_secret_access_key
    source: /go/src/bosun.org/cmd/scollector/scollector
    target: /artifacts/scollector/${DRONE_TAG}/scollector
    strip_prefix: /go/src/bosun.org/cmd/scollector/scollector
    when:
      event: tag

  increment_version:
    image: 325714046698.dkr.ecr.eu-west-1.amazonaws.com/drone-plugins/increment-version
    version_file: version.txt
    when:
      branch: master
      event:
        exclude: pull_request
